// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0RRZCcb9fz_E9tFCcJMsBa1jWqorjvwI',
    appId: '1:160887946547:android:7296fd766faeaee1731246',
    messagingSenderId: '160887946547',
    projectId: 'example-cfc4c',
    storageBucket: 'example-cfc4c.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-y1I7WKsePMaQwNakZJwy8mfnBvNbsz0',
    appId: '1:160887946547:ios:53854519ef1b61ec731246',
    messagingSenderId: '160887946547',
    projectId: 'example-cfc4c',
    storageBucket: 'example-cfc4c.firebasestorage.app',
    androidClientId: '160887946547-8noq3607p916og2cfj26rv6k2qsrbd1b.apps.googleusercontent.com',
    iosClientId: '160887946547-u99ajt8iuf5ojd3qkqgcnv3d8s6st1si.apps.googleusercontent.com',
    iosBundleId: 'com.example.wardComplaintApp',
  );
}
